# Generated by Django 5.1.3 on 2024-11-24 22:02

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='کلمه نامناسب')),
            ],
            options={
                'verbose_name': 'کلمه نامناسب',
                'verbose_name_plural': 'کلمات نامناسب',
            },
        ),
        migrations.CreateModel(
            name='BlogCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='اسلاگ')),
                ('upload_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته بندی وبلاگ',
                'verbose_name_plural': 'دسته بندی وبلاگ ها',
            },
        ),
        migrations.CreateModel(
            name='CustomersSays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('image', models.ImageField(default='default/profile.jpg', upload_to='profile/customers/', verbose_name='عکس مشتری')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='packages/image/Originals/', verbose_name='تصویر اصلی دوره')),
                ('video', models.FileField(upload_to='packages/video/Originals/', verbose_name='ویدیو معرفی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت دوره')),
                ('is_sale', models.BooleanField(blank=True, default=False, null=True, verbose_name='تخفیف')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت پس از تخفیف')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پکیج آموزشی',
                'verbose_name_plural': 'پکیج های آموزشی',
            },
        ),
        migrations.CreateModel(
            name='ProjectsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='اسلاگ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته بندی پروژه',
                'verbose_name_plural': 'دسته بندی پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='services/', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('video', models.URLField(blank=True, null=True, verbose_name='ویدیو')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='نام فضای مجازی')),
                ('link', models.URLField(verbose_name='لینک')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لینک فضای مجازی',
                'verbose_name_plural': 'لینک های فضای مجازی',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('position', models.CharField(choices=[('founder', 'Founder'), ('co-founder', 'Co-founder'), ('ceo', 'CEO'), ('cto', 'CTO'), ('cfo', 'CFO'), ('hr-manager', 'HR Manager'), ('sales-manager', 'Sales Manager'), ('marketing-manager', 'Marketing Manager'), ('business-analyst', 'Business Analyst'), ('programming-team-lead', 'Programming Team Lead'), ('backend-developer', 'Backend Developer'), ('frontend-developer', 'Frontend Developer'), ('fullstack-developer', 'Full Stack Developer'), ('devops-engineer', 'DevOps Engineer'), ('mobile-developer', 'Mobile Developer'), ('qa-engineer', 'QA Engineer'), ('product-manager', 'Product Manager'), ('data-analyst', 'Data Analyst'), ('data-scientist', 'Data Scientist'), ('design-team-lead', 'Design Team Lead'), ('ui-ux designer', 'UI/UX Designer'), ('graphic-designer', 'Graphic Designer'), ('motion-designer', 'Motion Designer')], max_length=50, verbose_name='سمت')),
                ('description_duties', models.TextField(verbose_name='درباره وظایف')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('face_book_link', models.URLField(blank=True, null=True, verbose_name='لینک فیس بوک')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='لینک توییتر')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='لینک گیت هاب')),
                ('pinterest', models.URLField(blank=True, null=True, verbose_name='لینک پینترست')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('image', models.ImageField(upload_to=core.models.Blogs.get_upload_path, verbose_name='ویدیو')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blogcategories', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'وبلاگ',
                'verbose_name_plural': 'وبلاگ ها',
            },
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.BlogImages.get_upload_path, verbose_name='انتخاب تصویر')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_blogs', to='core.blogs')),
            ],
            options={
                'verbose_name': 'تصویر مرتبط با وبلاگ',
                'verbose_name_plural': 'تصاویر مرتبط با وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('comment', models.TextField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100), core.models.validate_no_bad_words], verbose_name='نظر')),
                ('upload_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ انتشار')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='core.blogs')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='PackageComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('comment', models.TextField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100), core.models.validate_no_bad_words], verbose_name='نظر')),
                ('upload_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ انتشار')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_comments', to='core.packages')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='PackagesEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasone', models.PositiveIntegerField(verbose_name='انتخاب فصل')),
                ('episode', models.PositiveIntegerField(verbose_name='انتخاب اپیزود')),
                ('episode_video', models.FileField(upload_to=core.models.PackagesEpisode.get_upload_path, verbose_name='ویدیو')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_episode', to='core.packages')),
            ],
            options={
                'verbose_name': 'اپیزود پکیج',
                'verbose_name_plural': 'اپیزودهای پکیج ها',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='projects/')),
                ('customer_name', models.CharField(max_length=50, verbose_name='نام مشتری')),
                ('project_type', models.CharField(choices=[('internal', 'داخلی'), ('external', 'خارجی')], default='external', max_length=50, verbose_name='نوع پروژه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ پایان')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectscategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='SaysDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='نظر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_says_description', to='core.customerssays')),
            ],
            options={
                'verbose_name': 'گفته مشتری',
                'verbose_name_plural': 'گفته های مشتریان',
            },
        ),
        migrations.CreateModel(
            name='SrviceImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.services')),
            ],
            options={
                'verbose_name': 'تصویر سرویس',
                'verbose_name_plural': 'تصاویر خدمات',
            },
        ),
    ]
