# Generated by Django 5.1.3 on 2024-11-25 14:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_badwords_blogcategories_customerssays_packages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تماس باید با 09 شروع شود و شامل 11 رقم باشد', regex='^09\\d{9}$')], verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'درخواست ارتباط',
                'verbose_name_plural': 'درخواست های ارتباط',
            },
        ),
        migrations.AddField(
            model_name='badwords',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='اسلاگ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
        migrations.CreateModel(
            name='PurchasedPackages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_package', to='core.packages', verbose_name='پکیج آموزشی')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_profile', to='core.profiles', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'پکیج خریداری شده',
                'verbose_name_plural': 'پکیج های خریداری شده',
            },
        ),
    ]
