# Generated by Django 5.1.3 on 2024-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacts_badwords_created_at_profiles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SrviceImages',
            new_name='ServiceImages',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='pinterest',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='website_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک وب سایت'),
        ),
    ]
