# Generated by Django 5.1.3 on 2024-11-26 15:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_srviceimages_serviceimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='default_profile',
            field=models.ImageField(default='default_profile.jpg', upload_to='default_profile/'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='request_type',
            field=models.CharField(choices=[('individual', 'فردی'), ('company', 'شرکت'), ('business_owner', 'صاحب کسب و کار / مغازه')], default='individual', max_length=50, verbose_name='نوع درخواست'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.BooleanField(default=False, verbose_name='پیگیری شد'),
        ),
        migrations.AddField(
            model_name='packagecomments',
            name='default_profile',
            field=models.ImageField(default='default_profile.jpg', upload_to='default_profile/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to=core.models.Blogs.get_upload_path, verbose_name='تصویر معرفی'),
        ),
    ]
