# Generated by Django 5.1.3 on 2024-11-27 13:26

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogcomments_default_profile_contacts_request_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBrands',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=50, verbose_name='اسم برند')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='لینک وب سایت')),
                ('image', models.ImageField(upload_to=core.models.AllBrands.get_upload_path, verbose_name='لوگو برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
    ]
