# Generated by Django 5.1.3 on 2024-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_allbrands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('icon', models.ImageField(upload_to='counters/icons/', verbose_name='آیکون')),
                ('count', models.PositiveIntegerField(verbose_name='تعداد')),
                ('delay', models.CharField(default='300ms', max_length=10, verbose_name='تاخیر انیمیشن')),
                ('color', models.CharField(default='#ffffff', max_length=50, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'شمارنده',
                'verbose_name_plural': 'شمارنده\u200cها',
            },
        ),
    ]
