# Generated by Django 5.1.3 on 2024-11-27 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_skills_skillsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='skillsection',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
            preserve_default=False,
        ),
    ]
