# Generated by Django 5.1.3 on 2024-11-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ctasection'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsection',
            name='title_2',
            field=models.CharField(default='', max_length=50, verbose_name='عنوان 2'),
            preserve_default=False,
        ),
    ]
