# Generated by Django 5.1.3 on 2024-11-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_skillsection_title_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIntroductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='service-introductions/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بخش معرفی خدمات',
                'verbose_name_plural': 'بخش های معرفی خدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویژگی')),
                ('step', models.IntegerField(verbose_name='مرحله')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.ImageField(upload_to='about/icons/', verbose_name='آیکون')),
                ('service_introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.serviceintroductions')),
            ],
            options={
                'verbose_name': 'ویژگی خدمات',
                'verbose_name_plural': 'ویژگی\u200cهای خدمات',
                'ordering': ['step'],
            },
        ),
    ]
