# Generated by Django 5.1.3 on 2024-11-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_serviceintroductions_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceintroductions',
            name='heading',
            field=models.CharField(default='', max_length=50, verbose_name='عنوان 1'),
            preserve_default=False,
        ),
    ]
