# Generated by Django 5.1.3 on 2024-11-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_teammembers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='', verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
