# Generated by Django 5.1.3 on 2024-11-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_services_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='slug',
            field=models.SlugField(default='', verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
