# Generated by Django 5.1.3 on 2024-12-01 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_bootcamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bootcamps',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان دوره'),
        ),
        migrations.AddField(
            model_name='bootcamps',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع دوره'),
        ),
        migrations.AddField(
            model_name='bootcamps',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
