# Generated by Django 5.1.3 on 2024-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_bootcamps_created_at_bootcamps_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamps',
            name='status',
            field=models.BooleanField(default=False, help_text='مثلا:فعال', verbose_name='وضعیت'),
        ),
    ]
